# -*- mode: ruby -*-
# vi: set ft=ruby :
require './config'

Vagrant.configure("2") do |config|
  config.vm.hostname = "#{APP_NAME}"
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "v"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "1024"
    vb.name = "#{APP_NAME}"
  end

  config.vm.synced_folder APP_HOME, "/opt/#{APP_NAME}"
end
